### ISSUE TITLE
the repo of ApplozicSwift is not available

### ISSUE THREAD

**Issue by nebpehtire** [Kommunicate-io/Kommunicate-SwiftUI-Sample#1]
The pod does not install since the applozicSwift repository is not accessible on github

**Comment by amntoppoKM** [comment]
@nebpehtire  This is an old Sample App, Please use the latest sample app which contains the correct pods to be installed.

https://github.com/Kommunicate-io/Kommunicate-iOS-SDK/tree/master/Example
